units:
  kw: cx
  kh: cy
  px: kw + 5
  py: kh + 5

points:
  zones:

    matrix:
      anchor.shift: [100, -100]  # Fix placement en Kicad sheet
      key:
        padding: kh
        spread:  kw
        origin: [-0.5kw, -0.5kh]
      columns:
        outer:
        pinky.key.stagger: 0.195kh
        ring.key:
          stagger: 0.6kh
          splay: -9
        middle.key:
          stagger: 0.35kh
          splay: -6
        index.key.stagger: -0.25kh
        inner.key.stagger: -0.195kh

      rows:
        bottom:
        home:
        top:

    thumb:
      key:
        padding: kh
        spread:  kw
        splay:   -16
        origin: [-0.5kw, -0.5kh]
      anchor:
        ref: matrix_index_bottom
        shift: [0, -1.4kh]
      columns:
        tucky.key.splay: 0
        comfy:
        reachy:

  mirror:
    ref: matrix_index_bottom
    distance: 5.2kw

outlines:
  keys:
    - what: rectangle
      where: true
      size: [kw - 1, kh - 1]

  center:
    - what: rectangle
      where.ref.aggregate.parts: [matrix_middle_top, thumb_reachy, mirror_thumb_reachy, mirror_matrix_middle_top]
      size: 5
      adjust.rotate: 45

  keys_2:
    - what: rectangle
      where: true
      size: 13.8

  plate:
    - name: keys_2
    - operation: add
      name: center

  electronics:
    # MCU / IO expander
    - what: rectangle
      where: mirror_matrix_middle_bottom
      adjust.shift: [-0.15kw, -1.15kh]
      asym: both
      size: 10
    # Trackpad
    - what: circle
      where.ref.aggregate.parts: [matrix_inner_bottom, mirror_matrix_inner_bottom]
      radius: 40 / 2
      adjust.shift: [0, -8]

  board:
    - what: polygon
      operation: stack
      fillet: 5
      points:
        - ref: thumb_reachy
          shift: [0.65px, 0.5py]

        - ref: thumb_reachy
          shift: [0.5px, -0.55py]
        - ref: thumb_reachy
          shift: [-0.5kw, -0.55py]
        - ref: thumb_tucky
          shift: [0.5kw, -0.55py]
        - ref: thumb_tucky
          shift: [-0.55px, -0.55py]
        - ref: thumb_tucky
          shift: [-0.55px, -0.1py]
        - ref: matrix_pinky_bottom
          shift: [px, -0.75py]
        - ref: matrix_pinky_bottom
          shift: [0.5px, -0.65py]
        - ref: matrix_outer_bottom
          shift: [0.5px, -0.5py]
        - ref: matrix_outer_bottom
          shift: [0px, -0.5py]
        - ref: matrix_outer_bottom
          shift: [-0.5px, -0.5py]
        - ref: matrix_outer_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_pinky_top
          shift: [-0.5kw, 0.75py]
        - ref: matrix_ring_top
          shift: [-0.5kw, 0.55py]
        - ref: matrix_middle_top
          shift: [-0.5kw, 0.55py]
        - ref: matrix_middle_top
          shift: [0.5kw, 0.6py]
        - ref: matrix_index_top
          shift: [0.5px, 0.75py]

        - aggregate.parts: [matrix_inner_top, mirror_matrix_inner_top]
          shift: [0, 0.525py]

        - ref: mirror_matrix_index_top
          shift: [0.5px, 0.75py]
        - ref: mirror_matrix_middle_top
          shift: [0.5kw, 0.6py]
        - ref: mirror_matrix_middle_top
          shift: [-0.5kw, 0.55py]
        - ref: mirror_matrix_ring_top
          shift: [-0.5kw, 0.55py]
        - ref: mirror_matrix_pinky_top
          shift: [-0.5kw, 0.75py]
        - ref: mirror_matrix_outer_top
          shift: [-0.5px, 0.5py]
        - ref: mirror_matrix_outer_bottom
          shift: [-0.5px, -0.5py]
        - ref: mirror_matrix_outer_bottom
          shift: [0px, -0.5py]
        - ref: mirror_matrix_outer_bottom
          shift: [0.5px, -0.5py]
        - ref: mirror_matrix_pinky_bottom
          shift: [0.5px, -0.65py]
        - ref: mirror_matrix_pinky_bottom
          shift: [px, -0.75py]
        - ref: mirror_thumb_tucky
          shift: [-0.55px, -0.1py]
        - ref: mirror_thumb_tucky
          shift: [-0.55px, -0.55py]
        - ref: mirror_thumb_tucky
          shift: [0.5kw, -0.55py]
        - ref: mirror_thumb_reachy
          shift: [-0.5kw, -0.55py]
        - ref: mirror_thumb_reachy
          shift: [0.5px, -0.55py]


  combo:
    - name: board
    - operation: subtract
      name: keys
    - operation: subtract
      name: electronics

pcbs.quacken:
  # outlines.main.outline: center
  footprints:
    board_outline:
      what: outline
      where.ref.aggregate.parts: [matrix_middle_top, thumb_reachy, mirror_thumb_reachy, mirror_matrix_middle_top]

    choc_main:
      what: choc_but_better
      where: -/inner|outer/
      adjust.rotate: 180
      params:
        hummingbird: /pinky_(home|bottom)/
        from: "{{colrow}}"  # Placeholder, net is actually defined in kicad schematic
        to: "GND"

    choc_extensions:
      what: choc_but_better
      where: /inner|outer/
      params:
        hummingbird: -/bottom/
        from: "{{colrow}}"  # Placeholder, net is actually defined in kicad schematic
        to: "GND"

    usb_connector:
      what: usb_c
      where: matrix_pinky_top
      adjust.shift: [8.5, 15.3]

    qwiic:
      what: qwiic
      where: mirror_matrix_pinky_top
      adjust.shift: [8.5, 15.3]
      adjust.rotate: 180

    # Ergogen’s trrs jack footprint is not fucking centered
    trrs_left:
      what: trrs
      where: matrix_inner_bottom
      adjust:
        shift: [32.2, -13]
        rotate: -90 + 15
      params:
        A: "I2C_SCL"
        B: "I2C_SDA"
        C: "+3V3"
        D: "GND"

    trrs_right:
      what: trrs
      where: mirror_matrix_inner_bottom
      adjust:
        shift: [31.0, -8.55]
        rotate: -90 + 15
      params:
        A: "I2C_SCL"
        B: "I2C_SDA"
        C: "+3V3"
        D: "GND"

    rotaries:
      what: rotary
      where: /thumb_(tucky|reachy)/
      adjust.rotate: 180
      params:
        from: "{{colrow}}"
        to: "GND"
        A: "{{colrow}}_A"
        B: "{{colrow}}_B"
        C: "GND"

    dummy_cirque:
      what: dummy_cirque
      where.ref.aggregate.parts: [matrix_inner_bottom, mirror_matrix_inner_bottom]
      adjust.shift: [0, -8]

    cirque:
      what: cirque
      where: /inner_bottom/
      adjust:
        rotate: 270 + 15
        shift: [18, -3.5]
