on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: Nuclear-Squid/Quacken/.github/workflows/build-user-config.yml@zmk_firmware
    with:
      build_matrix_path: firmware/zmk/build.yml
      config_path: firmware/zmk/config
